# Generated by Django 4.2.1 on 2023-06-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_no', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=150)),
                ('user_image', models.ImageField(upload_to='userProfile')),
                ('dob', models.DateField(null=True)),
                ('user_bio', models.CharField(max_length=150)),
                ('type', models.CharField(default='user', max_length=100)),
                ('address', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_no', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=150)),
                ('user_image', models.ImageField(upload_to='workerProfile')),
                ('dob', models.DateField(null=True)),
                ('user_bio', models.CharField(max_length=150)),
                ('type', models.CharField(default='worker', max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('job_title', models.CharField(max_length=150, null=True)),
                ('catagory', models.CharField(max_length=150, null=True)),
                ('experience', models.CharField(max_length=150, null=True)),
                ('skill_1', models.CharField(max_length=150, null=True)),
                ('skill_2', models.CharField(max_length=150, null=True)),
                ('skill_3', models.CharField(max_length=150, null=True)),
                ('id_proof', models.ImageField(upload_to='workerProfile')),
                ('exp_proof', models.ImageField(upload_to='workerProfile')),
                ('cv', models.ImageField(upload_to='workerProfile')),
                ('is_approved', models.BooleanField()),
                ('status', models.BooleanField()),
                ('report', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
