# Generated by Django 4.2.1 on 2023-07-17 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_worker_is_approved_alter_worker_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='cv',
            field=models.ImageField(upload_to='workerfile'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='exp_proof',
            field=models.ImageField(upload_to='workerfile'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_proof',
            field=models.ImageField(upload_to='workerfile'),
        ),
        migrations.CreateModel(
            name='job_post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=150)),
                ('job_description', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('min_wage', models.CharField(max_length=150)),
                ('max_wage', models.CharField(max_length=150)),
                ('exp_lvl', models.CharField(max_length=150)),
                ('expected_time', models.TimeField()),
                ('valid', models.BooleanField()),
                ('photo', models.ImageField(upload_to='job_post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
