# Generated by Django 4.2.1 on 2023-07-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_user_id_job_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='expected_time',
            field=models.CharField(max_length=100),
        ),
    ]
