# Generated by Django 4.2.1 on 2023-08-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='worker',
        ),
    ]
